### ISSUE TITLE
Progress indicator in sqlite_migration

### ISSUE THREAD

**Issue by jesterhodl** [scsibug/nostr-rs-relay#100]
```
Mar 03 20:56:59.830  INFO nostr_rs_relay::repo::sqlite_migration: DB version = 11
Mar 03 20:56:59.830  INFO nostr_rs_relay::repo::sqlite_migration: database schema needs update from 11->12
Mar 03 20:56:59.830  INFO nostr_rs_relay::repo::sqlite_migration: updating replaceable events; this could take awhile...
```
Could this output something like: 10%, 20%?

**Comment by scsibug** [comment]
Sure, there is a good pattern in the later migrations that outputs a live progress bar.  I didn't add it in to earlier migrations just because they only get hit once and never seen again.  Future migrations should be much friendlier though.
