### ISSUE TITLE
relay not readable

### ISSUE THREAD

**Issue by itasli** [scsibug/nostr-rs-relay#103]
I have two nostr relay, one that i build and the other using docker image, when i check for relay information on [https://nostr.watch](https://nostr.watch) i got "not redeable" for the one running on docker they both have the same config file

**Comment by mroxso** [comment]
I'm using this Docker Image as well (in a Kubernetes Cluster) and it works fine for me.
https://nostr.watch/relay/nostr.0x50.tech

**Comment by PastaGringo** [comment]
Hi @itasli, I have the same issue, did you find where the issue comes from ? Thanks

**Comment by thesimplekid** [comment]
Are you able to access the relay locally?  Are you using a reverse proxy?

**Comment by PastaGringo** [comment]
Yes and yes. 
Reverse proxy through an Nginx container to the nostr-rs-relay container listening on 8080 (a little bit exotic).
The websocket is connected on websocketking. Currently node is online on nostr.watch but not readable/writable.
Here is the Nginx template config file :
```
server {
    listen       80;
    listen  [::]:80;
    server_name  $LINK_DOMAIN_DEFAULT;

    #access_log  /var/log/nginx/host.access.log  main;

        location / {

                proxy_http_version 1.1;
                proxy_pass http://nostr-relay-fractal:8080;
                proxy_set_header Connection $http_connection;
                proxy_set_header Upgrade $http_upgrade;
        }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}
```
Currently testing with https://github.com/0xtrr/nostr-tool

**Comment by thesimplekid** [comment]
Its not readable on nostr.watch but are you able to read and write to it with nostr tool?

**Comment by PastaGringo** [comment]
It seems to be working fine finally : 

```
nostr-tool -r wss://coeditor-congested.fractalnetworks.co/ text-note -c "Hello World"
No private key provided, creating new identity
Private key: nsec1qqxqjmhdz84ydts98wt7md03s5suzd2jxgvamhs6te5xt8nf8frq2r53d9
Public key: npub1ywk6re02k3fma6rf7metxtmsfh0fq0vkruuwd0fvp0vhgfhg7jeqsr4txp
Published text note with id: note1xshlx30qa5gy8dly78xzz333wc3td8rmy5q0l42xfd5z3cldws5qxkz964
nostr-tool -r wss://coeditor-congested.fractalnetworks.co/ list-events
0: {
  "id": "342ff345e0ed1043b7e4f1cc2146317622b69c7b2500ffd5464b6828e3ed7428",
  "pubkey": "23ada1e5eab453bee869f6f2b32f704dde903d961f38e6bd2c0bd97426e8f4b2",
  "created_at": 1678647133,
  "kind": 1,
  "tags": [],
  "content": "Hello World",
  "sig": "228c7ce99e0b45a939684a3c7f917569fdb68b4fdc33304a011517eb2c243fe2e33320a632f31b52e2682b5739a629968e229c11854f2392f625e2d09c96ccd1"
}
```
Nostr.watch is maybe checking things in a different way. I didn't find yet the code that tests the read/write services from a relay in the [nostr.watch source](https://github.com/dskvr/nostr-watch)

**Comment by PastaGringo** [comment]
And btw I found the note ID on relays by going checking here: https://nrcheck.tigerville.no/

**Comment by itasli** [comment]
I did some test, and it looks like cloning and building the image myself using the included Dockerfile and running it solves my issue, but if I use the image provided on dockerhub the issue persists. @PastaGringo you had a similare issue would you be able to test what i described ?

**Comment by dskvr** [comment]
> Nostr.watch is maybe checking things in a different way. 
It's subscribing and waiting for events, it does have a timeout, otherwise the site would be easily broken and would take a few hours to load. 

> I didn't find yet the code that tests the read/write services from a relay in the [nostr.watch source](https://github.com/dskvr/nostr-watch)****

Should have read the `README.md`, it links to [nostrwatch-js](https://github.com/dskvr/nostrwatch-js)
