### ISSUE TITLE
subscribe with prefixed filter ids (nip-01)

### ISSUE THREAD

**Issue by offbyn** [scsibug/nostr-rs-relay#104]
I'd like to subscribe to event ids starting with "0" as described in nip-01, but it seems no relays support that yet. Reason: there are some clients that support nip-13 POW and add nonce tag, but filtering by nonce on the client still means that all events are subscribed too which results in lots of bandwidth usage. Therefore I'd like to only subscribe to events starting with '0' or '00' 

> `"ids": <a list of event ids or prefixes>`
> The ids and authors lists contain lowercase hexadecimal strings, which may either be an exact 64-character match, or a prefix of the event value. A prefix match is when the filter string is an exact string prefix of the event value. The use of prefixes allows for more compact filters where a large number of values are queried, and can provide some privacy for clients that may not want to disclose the exact authors or events they are searching for.

https://github.com/nostr-protocol/nips/blob/master/01.md

example: `filter: { ids: ['0'] }`

**Comment by scsibug** [comment]
This already works.  Is there an example filter/req that is not returning the events you expect?

**Comment by scsibug** [comment]
We also support this for non-aligned (odd-length) hex prefixes, which is a bit trickier.  Did you actually test this against a real relay?

**Comment by hoytech** [comment]
I didn't notice that you did the work to support odd-length prefixes, nice one! With strfry I punted on that -- didn't seem worth the trouble.

**Comment by offbyn** [comment]
Great to know that it is supported, now I assume I prob made some mistake from upgrading nostr-tools 0.x to 1.6..

please bear with me. I tried to make a minimal example JSFIDDLE, that is supposed console log and subscribe to 2 events of kind: 1 to id's starting with '0'.

I don't get any events though. If the ids are removed it seems to receive 2 events with kind 1. 
 https://jsfiddle.net/pbdrwo53/1/

here is an event that I made that should start with 0's
- https://snort.social/e/note1qqqvjav385rswn8r4ql727w6w86fmj3v8tkj5vdphr7h2ng9shxqplevaf
- https://www.nostr.guru/e/0000c975913d07074ce3a83fe579da71f49dca2c3aed2a31a1b8fd754d0585cc

afaik the relay is using nostr-rs-relay `curl -H 'accept: application/nostr+json' https://relay.snort.social/` shows
 "software": "https://github.com/v0l/nostr-rs-relay",
  "version": "0.8.7"

**Comment by offbyn** [comment]
> We also support this for non-aligned (odd-length) hex prefixes, which is a bit trickier.

I'd love to read more about that.

**Comment by scsibug** [comment]
> > We also support this for non-aligned (odd-length) hex prefixes, which is a bit trickier.
> 
> I'd love to read more about that.

The source file that implements this is https://github.com/scsibug/nostr-rs-relay/blob/master/src/hexrange.rs

The basic idea is to take a single hex string (of any length) and determine the search strategy; either an exact match, a range between two byte arrays, or a single lower bound that all results must be greater than.

Hopefully the test cases help shed some light on that also, especially the ones that deal with an overflow - "abf" turns into a search range of bytes 0xABF0 to 0xAC00.  Sqlite can use a very fast memcmp() operation as a result, instead of a text substring search.

**Comment by offbyn** [comment]
oups I actually see some events, they are just not logged somehow. I am somehow not using nostr-tools correctly.

closing this issue


![Screen Shot 2023-03-12 at 2 47 53 PM](https://user-images.githubusercontent.com/55983159/224548973-32bb6532-f1de-4e44-a240-dfd51682e603.png)

**Comment by offbyn** [comment]
looks like nostr-tools is going to get support for nip-01 prefix. https://github.com/nbd-wtf/nostr-tools/pull/158

@scsibug the nip only mentions prefixes for "ids" and "authors" filter, but thinking more about it: I guess it could also make sense for "#p" and "#e" filters, what do you think?

is that something that should be added to nip-01 and nostr-rs-relay woudl support?

**Comment by scsibug** [comment]
Sure, it could make sense, but I think it's better (for relay implementations) to not have any special treatment on the tag values, and treat them opaquely.  Honestly, I think prefix search on ids/authors was probably too clever and I wouldn't propose it again if we could do it over (I wouldn't remove it now, but it does set a poor precedent).

So, no, I would push back against this in NIP-01.  Other NIPs that included relay-dependent behavior based on tag values would also have a very high bar for me.  "Smart clients dumb relays" is a good motto here.

Someone could do an analysis on the big clients (amethyst, snort, damus, etc.) and see how many actually use prefix search for ids/authors; I would expect the answer to be "none" - in which case, maybe prefix search was a mistake all along...

**Comment by offbyn** [comment]
> Honestly, I think prefix search on ids/authors was probably too clever and I wouldn't propose it again if we could do it over (I wouldn't remove it now, but it does set a poor precedent).

why was it a mistake? nostr-tools doesn't even support it yet, it just got merged but not published.

I'd love to use it for only receiving nip-13 POW events, which all the big clients don't support anyway afaik. just because they are big and all focus on nip-05 doesn't mean this is not useful.

another reason is privacy, but then if you reveal which exact events tag you want the prefix in ids doesnt help with privacy. (ofc it still helps in case of subscribing only to mined events).

**Comment by offbyn** [comment]
maybe it is not optimal that it is part of nip-01, and it would have been better to have it's own nip for prefixes, so relay can support prefix or not.

**Comment by scsibug** [comment]
Yep, i agree with that.
