### ISSUE TITLE
failed to run custom build command

### ISSUE THREAD

**Issue by tomnick** [scsibug/nostr-rs-relay#105]
hi, I am trying to install my relay following the guide at https://github.com/BlockChainCaffe/Nostr-Relay-Setup-Guide on Ubuntu 20.04.  At the step "Compile nostr-rs"  

`cd /opt
mkdir nostr-data
git clone https://github.com/scsibug/nostr-rs-relay.git
cd nostr-rs-relay
cargo build --release `

I am getting the following error:

error: failed to run custom build command for nostr-rs-relay v0.8.8 (/opt/nostr-rs-relay)`

Caused by:
process didn't exit successfully: /opt/nostr-rs-relay/target/release/build/nostr-rs-relay-e52fd45d8c8d75ad/build-script-build (exit status: 1)
--- stdout
cargo:rerun-if-changed=proto/nauthz.proto
cargo:rerun-if-changed=proto

--- stderr
Error: Custom { kind: Other, error: "protoc failed: Unknown flag: --experimental_allow_proto3_optional\n" }

`Any idea what could be wrong?

**Comment by thesimplekid** [comment]
The protobuf compiler is too old 

https://github.com/scsibug/nostr-rs-relay/issues/83

**Comment by pfergi42** [comment]
I think I had to do this to get past this:

https://lindevs.com/install-protoc-on-ubuntu
