### ISSUE TITLE
Feature Proposal: Rate Limiting Per npub

### ISSUE THREAD

**Issue by libertas-primordium** [scsibug/nostr-rs-relay#106]
I'm not sure how big of an ask this would be, but rate limiting of events per npub would be a very powerful anti-spam tool.
Currently rate limiting all incoming events can punish good users simply because a few spammers might be blasting out so many events per minute.

**Comment by 0xtrr** [comment]
This could stop some spammers but in my experience, the worst spammers create new keypairs every time they post

**Comment by scsibug** [comment]
Agreed, lots of spam comes from the same IP, but the pubkey varies.  gRPC filters are the best defense against this at the moment.
