### ISSUE TITLE
Could not parse hex range

### ISSUE THREAD

**Issue by mroxso** [scsibug/nostr-rs-relay#108]
When I try to view an event or a profile with the cli tool "noscl" (`noscl profile npub1sg6plzptd64u62a878hep2kev88swjh3tw00gjsfl8f237lmu63q0uf63m`), I get the following error on nostr-rs-relay side:
`INFO nostr_rs_relay::repo::sqlite: Could not parse hex range from author "npub1sg6plzptd64u62a878hep2kev88swjh3tw00gjsfl8f237lmu63q0uf63m"`

Any idea what I'm doing wrong?

**Comment by denis2342** [comment]
replace your nbpub with this: 82341f882b6eabcd2ba7f1ef90aad961cf074af15b9ef44a09f9d2a8fbfbe6a2

**Comment by mroxso** [comment]
how did you achieve this? isnt it from ascii to hex conversion?

**Comment by mroxso** [comment]
thank you very much
