### ISSUE TITLE
Warning: Connection reset by peer

### ISSUE THREAD

**Issue by pfergi42** [scsibug/nostr-rs-relay#112]
Am seeing more and more of these warnings in the logs. Not sure if it's a problem or not:

`[2mMar 31 20:47:25.153[0m [33m WARN[0m nostr_rs_relay::server: IO error (cid: 01555b9b, ip: "127.0.0.1"): Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }`

**Comment by scsibug** [comment]
Unlikely to be your issue.  If a client loses their connection, that'll trigger client errors like that.  Pretty normal when dealing with web/mobile clients.
