### ISSUE TITLE
Delete DMs

### ISSUE THREAD

**Issue by mattn** [scsibug/nostr-rs-relay#117]
Sorry, I'm not sure that this is related on nostr-rs-relay. I hope to delete my broken DM. But AFAICS, nostr-rs-relay does accept kind 5 for DM (kind 4). Could you please support deletion for DM?

**Comment by 0xtrr** [comment]
I don't think there is any special handling for DMs when the relay gets a kind 5 event? Upon receiving the kind 5 event, the referenced event is hidden and will not be brodcasted on the websockets. 

https://github.com/scsibug/nostr-rs-relay/blob/ba0b50bc9c7aef177d23ba38d3a371cce0e5f11b/src/repo/sqlite.rs#L206

To actually remove them from the database, check out this guide: https://github.com/scsibug/nostr-rs-relay/blob/master/docs/database-maintenance.md#clearing-hidden-events

**Comment by mattn** [comment]
Sorry, this is caused that wss.snort.social became payed relay recently.
