### ISSUE TITLE
Please add nginx configuration to the documentation

### ISSUE THREAD

**Issue by Giszmo** [scsibug/nostr-rs-relay#12]
I try to reverse-proxy on nginx and don't know how it should look such that it's nip-11 compliant aka without using a different url for page and ws. Please amend https://github.com/scsibug/nostr-rs-relay/blob/master/reverse-proxy.md accordingly.

**Comment by scsibug** [comment]
I'm happy to add documentation, but I don't actually use NGINX for front-ending any nostr relay instances.

If anyone has a config they like, please feel free to open a PR or send a patch.

**Comment by plantimals** [comment]
I host  `nostr.drss.io` on ubuntu 20.04 using the following:

```
http {
	server {
		listen 443 ssl;
		server_name nostr.drss.io;
		ssl_certificate /etc/letsencrypt/live/nostr.drss.io/fullchain.pem;
		ssl_certificate_key /etc/letsencrypt/live/nostr.drss.io/privkey.pem;
		ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
		ssl_ciphers HIGH:!aNULL:!MD5;
		keepalive_timeout 70;

		location / {
			proxy_pass http://localhost:<local port>;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "Upgrade";
			proxy_set_header Host $host;
		}
	}
}
```
with the `<local port>` bit replaced with the port I config `nostr-rs-relay` to run on. obviously I am using letsencrypt for ssl keys, so you'll need to get all that setup if you want https connections. I found [this resource](https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-20-04) to be particularly useful in getting that done.

**Comment by scsibug** [comment]
Yes, please open a PR and add content to the reverse-proxy.md file.  That would be a great addition as it seems more people run nginx than haproxy.  Thanks!
