### ISSUE TITLE
Questions about "repost".

### ISSUE THREAD

**Issue by cxplay** [scsibug/nostr-rs-relay#122]
I've set my relay so that only my own public key is available, but it doesn't seem to save "repost"? I don't quite understand the details of this, does this mean I have to add the public key of the user included with the "repost" event to the whitelist as well?

**Comment by thesimplekid** [comment]
Using the whitelist is somewhat limited in that only events posted by whitelisted keys (your key in this case) will be allowed by the relay. 

I think there are a few different ways reposts are implemented by clients as there were some older nips that were change/removed. But with current [NIP-18](https://github.com/nostr-protocol/nips/blob/master/18.md) reposts if you whitelisted only your key, your relay would allow the repost event but not the event you are re posting.  

There is a second issue here as well in that the relay does not fetch events, so even if you whitelisted the pubkey of the author of the event you are reposing, if you or your client does not rebroadcast the event, your relay still wont have it.

You may be interested in this gRPC extension for the relay that allows and fetches events the primary key or keys interact with https://github.com/thesimplekid/my-local-nostr

**Comment by cxplay** [comment]
> Using the whitelist is somewhat limited in that only events posted by whitelisted keys (your key in this case) will be allowed by the relay.
> 
> I think there are a few different ways reposts are implemented by clients as there were some older nips that were change/removed. But with current [NIP-18](https://github.com/nostr-protocol/nips/blob/master/18.md) reposts if you whitelisted only your key, your relay would allow the repost event but not the event you are re posting.
> 
> There is a second issue here as well in that the relay does not fetch events, so even if you whitelisted the pubkey of the author of the event you are reposing, if you or your client does not rebroadcast the event, your relay still wont have it.
> 
> You may be interested in this gRPC extension for the relay that allows and fetches events the primary key or keys interact with https://github.com/thesimplekid/my-local-nostr

Thank you very much, let me take a look.

**Comment by cxplay** [comment]
I didn't realize that the "repost" operation hadn't been standardized yet, and I'm not very familiar with programming techniques, so I'll probably use "quote" for now instead...

**Comment by cxplay** [comment]
Very strange question, why NIP-18 should save "repost" without a context. If it is to be implemented, the repost should include at least one context, as in the case of "quote", which should be an operation like "quote" and "reply".
Sorry to bother you, maybe I should go to NIP-18 and make some suggestions.🙂

**Comment by thesimplekid** [comment]
> I didn't realize that the "repost" operation hadn't been standardized yet

It is "standardized" as a merged NIP, I just remember there were clients where it was implemented differently but they should be fixed by now. A quote will still have the same issue as you won't have the event you're quoting its self. 

> Very strange question, why NIP-18 should save "repost" without a context. If it is to be implemented, the repost should include at least one context, as in the case of "quote", which should be an operation like "quote" and "reply". Sorry to bother you, maybe I should go to NIP-18 and make some suggestions.slightly_smiling_face

I would take a look through here here https://github.com/nostr-protocol/nips/pull/140

**Comment by cxplay** [comment]
> > I didn't realize that the "repost" operation hadn't been standardized yet
> 
> It is "standardized" as a merged NIP, I just remember there were clients where it was implemented differently but they should be fixed by now. A quote will still have the same issue as you won't have the event you're quoting its self.
> 
> > Very strange question, why NIP-18 should save "repost" without a context. If it is to be implemented, the repost should include at least one context, as in the case of "quote", which should be an operation like "quote" and "reply". Sorry to bother you, maybe I should go to NIP-18 and make some suggestions.slightly_smiling_face
> 
> I would take a look through here here [nostr-protocol/nips#140](https://github.com/nostr-protocol/nips/pull/140)

Thanks, I'll take a closer look.

**Comment by cxplay** [comment]
I'm back! I tried your project: https://github.com/thesimplekid/my-local-nostr. So great! but there is still some confusion, why does nostr-rs-relay choose pass by default for events that do not pass the gRPC server validation? 
For someone who has explicitly set up a gRPC server, since they obviously want to filter events entirely through the gRPC server, and if the server is not accessible then relay should choose to reject(Especially for personal relay servers). 
So I think there is a choice of default deny or default pass?

**Comment by scsibug** [comment]
Yes, I made the decision initially to make this default-permit as I developed the first gRPC server, and I did not want to block events as I was playing with it.

It makes more sense now to make this configurable, and default to deny.

**Comment by scsibug** [comment]
Tracking over on sr.ht (https://todo.sr.ht/~gheartsfield/nostr-rs-relay/76)
