### ISSUE TITLE
NIP-42 state, out of order events and queueing 

### ISSUE THREAD

**Issue by earonesty** [scsibug/nostr-rs-relay#128]
I have a question.   There apparently have been complaints about NIP-42, and it has apparently not been getting much traction. 

Would a stateless auth be better?  

https://github.com/nostr-protocol/nips/pull/571#issuecomment-1572786003

**Comment by scsibug** [comment]
Haven't gotten around to digging into this one, but seems worth an investigation.

**Comment by earonesty** [comment]
there is a NIp43.   it's stateless, fast and it works well for me.
