### ISSUE TITLE
Publish docker image to public registry

### ISSUE THREAD

**Issue by theborakompanioni** [scsibug/nostr-rs-relay#13]
Would you consider publishing the docker image publicly?
Or is that something you don't like and rule out in advance?

e.g. GitHub's `ghcr.io` ([Working with the Container registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)) or somewhere else..

Your effort is highly appreciated. Thank you for your work on this amazing relay :rocket:

**Comment by scsibug** [comment]
I try to keep the DockerHub repository up-to-date here: https://hub.docker.com/r/scsibug/nostr-rs-relay (there is a link in the README as well).

Is that what you are looking for, or are there other hosting repos like GHCR that would make sense to publish as well?

**Comment by theborakompanioni** [comment]
> I try to keep the DockerHub repository up-to-date here: https://hub.docker.com/r/scsibug/nostr-rs-relay (there is a link in the README as well).

Damn.. I don't know how I could have missed that.. please excuse my sloppiness.

> Is that what you are looking for, or are there other hosting repos like GHCR that would make sense to publish as well?

No.. not worth the extra effort, I think. DockerHub is perfectly fine.
