### ISSUE TITLE
JsonParseFailed(Error("missing field `paid`", line: 1, column: 36)

### ISSUE THREAD

**Issue by gazhayes** [scsibug/nostr-rs-relay#134]
When using the http interface to get an invoice, new pubkeys are fine but pubkeys with an existing entry in the db fail sometimes (no response).

`error in payment: JsonParseFailed(Error("missing field `paid`", line: 1, column: 36))`

I suspect that this is because LNbits no longer has the invoice (expired).

I can see that the request to LNBits has an expiry of `3600` included, but it looks like we are still calling the LNbits API for the invoice after expiry.

I'll keep digging and try to fix this and send a pull request, but if someone can point me in the right direction that would be awesome.

**Comment by thesimplekid** [comment]
Hey, thanks for reporting this, check out #135

**Comment by gazhayes** [comment]
Hey @thesimplekid that fixes it! Thanks!
