### ISSUE TITLE
Problem: can't turn off pay-to-relay DMs

### ISSUE THREAD

**Issue by gazhayes** [scsibug/nostr-rs-relay#137]
I'd like to turn off DMs. I've done this in my fork simply by commenting out the relevant line https://github.com/scsibug/nostr-rs-relay/commit/7076ea8a7664e70ab499641dd12a2fb2e3452896

Would be cool to have this as a config option though.

Just logging this here to keep track of the issue, if no one adds this feature I'll do it sooner or later.

**Comment by thesimplekid** [comment]
Config option added in #138
