### ISSUE TITLE
Feature request: live loading of blacklist/whitelist

### ISSUE THREAD

**Issue by gazhayes** [scsibug/nostr-rs-relay#143]
Can blacklist/whitelist be live-loaded instead of loaded once at startup?

Or could the owner of the relay send events to add to the whitelist/blacklist?

I don't have a whole lot of time right now to implement this myself so I'd be happy to send some sats

**Comment by thesimplekid** [comment]
Take a look at this grpc extension https://github.com/thesimplekid/manage-relay-users

**Comment by gazhayes** [comment]
Amazing!

I haven't used gRPC etc before, can you give me some pointers on how to deploy this? Once I've got it working I'll send a PR with some documentation.

**Comment by thesimplekid** [comment]
Yeah needs better docs sorry about that.  You'll need to build the binary once you do so you can run it just like the binary for the relay with the argument `--config` to set the config file path. 

There is an example config in the repo that you can use so set authorized pubkeys. The keys listed here can add/remove pubkeys later so only set those you want to give that permission to, add the pubkeys you want to give write access to the relay later.  You can also set an api key here if you want to she http endpoints, just generate a random string. It is exposed on port 3000

In the relay config file you'll need to enable the grpc uncomment `event_admission_server = "http://127.0.0.1:50051"`

How are you running your relay? If you're using docker the networking will be different

**Comment by gazhayes** [comment]
Ok cool that all makes sense. 

I'm running it raw dog without docker, so loopback IP should work fine.

I'll try this out tomorrow. Don't bother doing documentation for this, I'll write it up as I go and send a PR.

**Comment by gazhayes** [comment]
This works perfectly, thanks @thesimplekid
