### ISSUE TITLE
nostr-rs-relay loads default settings if config file path cannot be read or found

### ISSUE THREAD

**Issue by irusensei** [scsibug/nostr-rs-relay#145]
The program will load the default settings if it cannot read the specified config file.

```
$ ./target/release/nostr-rs-relay --config /this/path/does/not/exist.toml
$ ss -ntlp | grep nostr-rs-relay
LISTEN 0      128          0.0.0.0:8080      0.0.0.0:*    users:(("nostr-rs-relay",pid=48156,fd=18))
```
The same will happen if the file cannot be read.

This might cause confusion as the user might be expecting their settings to be loaded. I think the most glaring problem for this would be the default port.

For example, due to a typo on my systemd unit config where I supplied a wrong config path the program loaded with default settings listening on port 8080 and preventing another program that uses the same port to load. 

Might also be the cause behind https://github.com/scsibug/nostr-rs-relay/issues/126.

I took the liberty of writing a small PR for the program to fail if config file does not exist or its unreadable: https://github.com/scsibug/nostr-rs-relay/pull/144

**Comment by scsibug** [comment]
Thanks, I agree that this has probably caused some difficulties for people getting started.

I do still like the process of allowing a default configuration to be used, but we should definitely incorporate your checks for the config file - when it is specified as a command line argument, we should error out if it was unreadable.

One of the big problems I noticed in reviewing this is that we use logging/tracing calls in the Settings/Config module prior to logging being initialized - these get thrown away.  I will add some eprintln calls to ensure parse errors are logged.

**Comment by scsibug** [comment]
I think the strategy should be:
 * If a config file was explicitly provided, we require it to exist and be well-formed.
 * If the config file was found implicitly (not provided as a CLI arg, but "config.toml" exists in the CWD), we use it if we can, and only emit a warning message if it is not parseable.

**Comment by scsibug** [comment]
Example of what this would look like.  I've intentionally added a syntax error to the config.toml file.

```
$ ./target/debug/nostr-rs-relay --config config.toml
Error reading config file (expected a right bracket, found a newline at line 3 column 8 in config.toml)

$ ./target/debug/nostr-rs-relay --config config.tomll
Config file not found: config.tomll

$ ./target/debug/nostr-rs-relay --config config.toml 
Error reading config file (expected a right bracket, found a newline at line 3 column 8 in config.toml)

$ ./target/debug/nostr-rs-relay                     
Error reading config file (expected a right bracket, found a newline at line 3 column 8 in config.toml)
WARNING: Default configuration settings will be used
2023-07-29T13:19:37.828685Z  INFO nostr_rs_relay: Starting up from main
...
```

**Comment by scsibug** [comment]
This example above was added to the main code base.
