### ISSUE TITLE
Images on Dockerhub not updating

### ISSUE THREAD

**Issue by hundehausen** [scsibug/nostr-rs-relay#153]
The latest image on [Dockerhub](https://hub.docker.com/r/scsibug/nostr-rs-relay/tags) is v0.8.9 (testing) and v0.8.8 (stable) but according to this repo we are at v0.8.12

**Comment by scsibug** [comment]
Just got behind on pushing over there, since my daily driver is ARM instead of x86.  Should be updated now, thanks for the reminder.
