### ISSUE TITLE
Postgres filter queries encoding the wrong value

### ISSUE THREAD

**Issue by arkaitzj** [scsibug/nostr-rs-relay#154]
It seems like there is a weird piece while encoding tag values for queries just in [here](https://github.com/scsibug/nostr-rs-relay/blob/34c8b04926ebc0d4feb78b1938a713fb84f37073/src/repo/postgres.rs#L888).
It checks for even length or hex characters before jumping into hex decoding as opposed to string to bytes.  
Is that what it is supposed to do? Because I queried `["#t", ["gaming_score"]]` and since its even it decodes with hex and goes to `None` so nothing is returned.
Is it possible the condition is backwards? `if even length && all_hex then do hex otherwise do bytes?` 
I removed the hex branch and my usecase works as expected now.  

Tagging @v0l since he shows up as the committer.

Thanks!

**Comment by v0l** [comment]
It should be fixed by https://github.com/scsibug/nostr-rs-relay/pull/164
