### ISSUE TITLE
Consider replace hyper-tls with hyper-rustls, don't rely on openssl ?

### ISSUE THREAD

**Issue by biluohc** [scsibug/nostr-rs-relay#156]
`sqlx = { version ="0.6.2", features=["runtime-tokio-rustls", "postgres", "chrono"]}`

You use sqlx with rustls also.

**Comment by scsibug** [comment]
Good idea.  Just got this working with just minor changes locally, will test a bit and commit.

**Comment by scsibug** [comment]
This is incorporated into 0.8.13, thanks for the suggestion.
