### ISSUE TITLE
Spam attack with direct_message=true. Is captcha possible?

### ISSUE THREAD

**Issue by decentropy** [scsibug/nostr-rs-relay#159]
I turned this on, because I thought it would be helpful to be notified if the relay got signups.

Someone pointed a bot at my relay signup page, and sent out 4800 DMs to random NOSTR users.
It took me a while to notice, now realizing that you won't see notifications in most nostr clients for sent DMs.

I am now sending 4800 delete requests, but thought I'd drop my learned lesson here for others
Plus... it would be nice feature to be able to customize the sign-up page... e.g. with a captcha type request. Is that possible?

**Comment by thesimplekid** [comment]
I'll change this to only send the admission message after payment is made, this should be enough to stop a spam attack. As you mention most nostr clients now don't show messages from keys you do not follow so the pre payment event isn't very useful as most users will never even see it as they use the web to sign up.  

These events are only sent to your relay so its likely the random nostr users have no idea about the events unless they've subscribed to your relay. So I believe the most damage done is to your LN node creating 4800 invoices that will never be paid. Maybe good to look into some rate limiting or spam prevention there.

**Comment by decentropy** [comment]
hopefully that'd stop them... but they could still spam lightning invoices. LNbits cancelled my api key due to the spam.

A rate limiter option in config, or ability to customize the join page with captcha would be ideal.

Closing issue, thanks!
