### ISSUE TITLE
Lightning address - Zap Pools

### ISSUE THREAD

**Issue by jackedproxy** [scsibug/nostr-rs-relay#161]
Hi,

I understand there are options to enable relay-payment but what I'm looking for is the option to add a lightning address for Zap Pools as a way for a user to split sats across a multitude of nostr services including the relay in question. 

Clients have begun to support this, as an example, this is an option on Snort.social - The user chooses percentages to split Zaps across relays, file hosts,  data providers, etc - https://snort.social/zap-pool

Perhaps I'm just missing something, but would appreciate any pointers.

**Comment by thesimplekid** [comment]
I have not kept up with but it is an interesting idea. One way I can think to support it is to simply add an ln address to the [NIP11](https://github.com/nostr-protocol/nips/blob/master/11.md) response. Do you know if any other relay implementations are supporting this?

**Comment by jackedproxy** [comment]
> I have not kept up with but it is an interesting idea. One way I can think to support it is to simply add an ln address to the [NIP11](https://github.com/nostr-protocol/nips/blob/master/11.md) response. Do you know if any other relay implementations are supporting this?

Not that I know of. 
I may have misinterpreted - Even though the Zap Pool option exists for other categories, the Relays category is empty and it could just be a placeholder of sorts.
I'll check with one of the Snort.social devs and report back with findings. 

I agree though, would be a great idea to get supporting relays via split-zaps in a very user-friendly manner with little  friction.
