### ISSUE TITLE
Filter Bug between versions 0.8.8 and 0.8.13

### ISSUE THREAD

**Issue by 42Pupusas** [scsibug/nostr-rs-relay#189]
**Description:**

Updated from version 0.8.8 to 0.8.13, built binaries on the same machine, binaries running on same server, same netwrok configurations.

The `authors` filter no longer matches any keys , returns all queries empty. 

**Sample Subscription Request:**

```
["REQ","OXx2ytLKWdQLEggQhbqvrUVQJjgS1cUX",{"kinds":[30042],"authors":["c7f8e9caab2d9ab681bd3319625fb0007d6bd393162aa776b12b8cdb90aa7752"]}]
```

- **Expected Behavior:**  Subrscription should return events of `kind` **30042** with filter `pubkey`.

- **Actual Behavior:** Returns 0 events.
- **Works For Version:** 0.8.8.
- **Does not Work For Version:** 0.8.13.

**Comment by scsibug** [comment]
Which database are you using for storage, sqlite or postgres?

**Comment by 42Pupusas** [comment]
I'm using the default configs mostly, so sqlite. Only thing I've changed from the default config.toml is the port number and relay name.

**Comment by lez** [comment]
This might be the same as https://todo.sr.ht/~gheartsfield/nostr-rs-relay/79
Fixed on master.

**Comment by scsibug** [comment]
Yep, should be fixed on master now.
