### ISSUE TITLE
How to troubleshoot the nostr-rs-relay setup ?

### ISSUE THREAD

**Issue by puppetninja** [scsibug/nostr-rs-relay#194]
Hi I am pretty new to nostr and nostr-rs-relay, I used docker-compose to deploy nostr-rs-relay and I constantly hit
```bash
WARN nostr_rs_relay::server: websocket response failed  
```
while test the setup with https://snowcait.github.io/nostr-playground/
```
CLOSE code: 1006, reason: 
ERROR
```
is all I got on client side, any pointer to troubleshooting the setup ?

I see the error is actually returned to the client seems
https://github.com/scsibug/nostr-rs-relay/blob/b04ab76e7305eb7585e94c20c5cd72e694cf9a20/src/server.rs#L155-L160

**Comment by Sjors** [comment]
I get the same error with a non-docker setup via Nginx. A more detailed error would be useful.

**Comment by Sjors** [comment]
In my case the underlying error was "WebSocket protocol error: HTTP version must be 1.1 or higher"

**Comment by scsibug** [comment]
If you want to get better logging, you can use `RUST_LOG` to bump up the level:
```
RUST_LOG=DEBUG ./target/debug/nostr-rs-relay
```
Level `TRACE` also works, but may be more than you want.

**Comment by Sjors** [comment]
@scsibug I don't think any log level would print the `error` variable here, it's unused. You would need to add a line `debug!(error)` below `warn!("websocket response failed"); `
