### ISSUE TITLE
Which Values Can Be Passed on Startup?

### ISSUE THREAD

**Issue by tsmith123** [scsibug/nostr-rs-relay#206]
I see that you can pass `--db` in the startup cmd but what else can be passed as it would be nice to avoid creating a toml file if possible.

For example, can I pass --description and --name etc?

**Comment by scsibug** [comment]
Pretty much the only command line arguments are --db for the database, and --config for the configuration file. (plus --help & --version).

Running `nostr-rs-relay --help` will print out the full list.

In [src/cli.rs](https://github.com/scsibug/nostr-rs-relay/blob/master/src/cli.rs ) you can see all the CLI args.
