### ISSUE TITLE
Build error: did not get container create message from subprocess: EOF

### ISSUE THREAD

**Issue by dtdannen** [scsibug/nostr-rs-relay#219]
> podman build --pull -t nostr-rs-relay .

WARN[0000] The cgroupv2 manager is set to systemd but there is no systemd user session available 
WARN[0000] For using systemd, you may need to log in using a user session 
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root) 
WARN[0000] Falling back to --cgroup-manager=cgroupfs    
[1/2] STEP 1/14: FROM docker.io/library/rust:1-bookworm AS builder
Trying to pull docker.io/library/rust:1-bookworm...
Getting image source signatures
Copying blob d83766a9c5ba done   | 
Copying blob b2b31b28ee3c done   | 
Copying blob 2112e5e7c3ff done   | 
Copying blob af247aac0764 done   | 
Copying blob c3cc7b6f0473 done   | 
Copying config d7ea9ee7bf done   | 
Writing manifest to image destination
[1/2] STEP 2/14: RUN apt-get update     && apt-get install -y cmake protobuf-compiler     && rm -rf /var/lib/apt/lists/*
error running container: from /usr/bin/crun creating container for [/bin/sh -c apt-get update     && apt-get install -y cmake protobuf-compiler     && rm -rf /var/lib/apt/lists/*]: sd-bus call: Interactive authentication required.: Permission denied
: exit status 1
ERRO[0025] did not get container create message from subprocess: EOF 
Error: building at STEP "RUN apt-get update     && apt-get install -y cmake protobuf-compiler     && rm -rf /var/lib/apt/lists/*": while running runtime: exit status 1
WARN[0025] Failed to add pause process to systemd sandbox cgroup: dbus: couldn't determine address of session bus

**Comment by dtdannen** [comment]
I recommend adding this to a FAQ or Troubleshooting section. The solution for me for this problem was:

sudo loginctl enable-linger $USER

Then re-login back to the server.

**Comment by scsibug** [comment]
I sympathize, this has bitten me on other projects when using rootless podman.  But I think it's such a well-documented podman issue now that I'd rather just consider it unrelated to this project for FAQ purposes (although of course, just having this issue will be a great help to many, so I thank you for making the issue).

There are a number of small gotchas with podman that are documented well here: https://rootlesscontaine.rs/getting-started/common/login/
