### ISSUE TITLE
Aligning on a Nix expression

### ISSUE THREAD

**Issue by jurraca** [scsibug/nostr-rs-relay#221]
Hi, I was about to update the nixpkgs nostr-rs-relay [package](https://github.com/NixOS/nixpkgs/blob/64b2f13b2eca9dd74653669ba5aab4a15b997f26/pkgs/by-name/no/nostr-rs-relay/package.nix) in anticipation of the 24.11 release, and I noticed you added a Nix flake in this [commit](https://github.com/scsibug/nostr-rs-relay/commit/0d04b5eefa2a50191fee4455ffd4de533e7487bc). 

It would be best to align on the method of building this package so we don't have two different ways of doing it. I'm open to removing the nixpkgs package entirely if no one is using it, in particular given nixpkgs infrastructure [struggles](https://discourse.nixos.org/t/infrastructure-announcement-the-future-of-ofborg-your-help-needed/56025). Otherwise I'm open to using the flake's `crane` based way if you think it's better. Let me know :) 

cc @JosephGoulden

**Comment by JosephGoulden** [comment]
Hi. I've wondered about the flake vs nixpkgs thing as well. 

As a user of nixos its very convenient to add something from nixpkgs into my shell or enable a service without having to add a flake input. But as a developer I _really_ like to use the flake as I have more options (especially with cargo).

As I understand it there is no way to import flakes into nixpkgs and there never will be, the point is to decentralise nixpkgs. And I don't think we will be able to use crane in nixpkgs either, its unnecessary.

I think it depends on the future of this project. If its going to be a big project and the developers use nix then crane is very useful, it gives you more features than buildRustPackage. If the project will have a lot of users then it might be worth maintaining nixpkgs and the flake.

Personally I am only using the flake.

**Comment by jurraca** [comment]
opened nixpkgs [PR](https://github.com/NixOS/nixpkgs/pull/360115) and closing this. If anyone has thoughts on the subject, feel free to reopen.

**Comment by scsibug** [comment]
Thanks for the discussion and work on this. I use NixOS a bit, but am still a novice, so I appreciate you all making this available.
