### ISSUE TITLE
Resource requirements for a relay?

### ISSUE THREAD

**Issue by ardevd** [scsibug/nostr-rs-relay#26]
Current running nostr-rs on an old RPI I had lying around but I have no idea what sort of resource requirements running a relay involves. Disk? RAM? CPU? What are the bottlenecks, if any? What sort of data does the relay store?

Thanks

**Comment by scsibug** [comment]
It all depends on how many clients you want to serve.  I suspect you will be limited only by the CPU of the Rpi.  Disk usage is minimal, and a couple of GB ram is plenty.  Running sql queries using CPU is the bottleneck, assuming you have a few megabits of network bandwidth.

The relay just stores a sqlite file, and any logs you choose to save.

**Comment by Giszmo** [comment]
This relay is definitely very low in demand for CPU and RAM. OP you tell us how it goes with an RPi! Benchmarks of the different relays are missing.

Else I guess this issue can be closed.
