### ISSUE TITLE
podman issue with tag and digest

### ISSUE THREAD

**Issue by Giszmo** [scsibug/nostr-rs-relay#29]
On Debian bullseye, the [current stable release](https://www.debian.org/releases/) I get this:

```
$ podman build -t nostr-rs-relay .
STEP 1: FROM docker.io/library/rust:1.66.0@sha256:359949280cebefe93ccb33089fe25111a3aadfe99eac4b6cbe8ec3e1b571dacb AS builder
STEP 2: FROM docker.io/library/debian:bullseye-20221205-slim@sha256:25f10b4f1ded5341a3ca0a30290ff3cd5639415f0c5a2222d5e7d5dd72952aa1
Error: error creating build container: Docker references with both a tag and digest are currently not supported
```

**Comment by scsibug** [comment]
I suspect that's just an old version of podman?  It's supported on latest Fedora.

But regardless, i'm going to stop bringing in the hash of the image.  We use a couple of trusted base images (debian & rust), and this will more easily let people re-build quickly for normal patching.

This should also let ARM people build more easily.

Try again and I bet it will work.
