### ISSUE TITLE
Please improve log output

### ISSUE THREAD

**Issue by Giszmo** [scsibug/nostr-rs-relay#32]
This might also be a question about how to improve log output. I started using this relay yesterday and the output is very spammy while not providing me key performance parameters.

Walls of 

```
Dec 21 18:49:09.641  INFO nostr_rs_relay::server: client sent duplicate subscription, ignoring (cid: dd299f44, sub: "D51FBDBA-5730-4C08-A90F-1D2BACAC0C12")
Dec 21 18:49:09.729  INFO nostr_rs_relay::server: client sent duplicate subscription, ignoring (cid: dd299f44, sub: "D51FBDBA-5730-4C08-A90F-1D2BACAC0C12")
```

flying by. On the other hand I'm missing statistical information.

Maybe some of the messages could get a lower - DEBUG - log level and have aggregate stats on INFO?

```
Dec 21 18:51:17.173  INFO nostr_rs_relay: 20s Stats
   566 sockets connected
   780 queries active
   153 events received
    51 new events persisted
    54 new events forwarded (includes 3 ephemeral events)
434321 events served from DB
 12345 suspicious events and requests. Start with --loglevel=DEBUG to show

```

**Comment by scsibug** [comment]
This would be a great feature (storing aggregate stats and displaying at INFO level on an interval).

I don't have any plans to implement this in the next few weeks, so if anyone wants to make an attempt and send a patch, that would be very interesting.
