### ISSUE TITLE
Relay rejecting valid event (kind: 5) 

### ISSUE THREAD

**Issue by dskvr** [scsibug/nostr-rs-relay#33]
Hey there, I've been stuck for about a day, and feel as though one of the following is happening:

1. I misread the NIP spec and am implementing wrong.
2. I misread the NIP spec and misinterpreted
3. This is a bug 

I've been seeking answers to no avail, and am running in circles at this point.

1. The event validates against event schema
2. The event signature validates
3. The ids exist on the relay where the event is being sent.
4. The `pubkey` of all the events (the ones being deleted AND the kind:5 event are identical) 
5. The ids are for an event kind in the `1000 -> 10000` range [basic events] _Could be that event kind `5` only works for specific event kinds? ... NIP didn't specify..._
6. Receive notice `could not parse command` [No `ok` received.]

Relay:
`0.7.13` 

Event: 
```
{
  content: 'updating relays',
  kind: 5,
  created_at: 1671853519,
  tags: [
    [
      'e',
      'b7584184b0d47adb7452ac18ccc4071635757ce3c4f530205b8be42d7a6b4ffd'
    ],
    [
      'e',
      'f0c8d9e4058d924b0b0bc98e7f83e2037afc74177cdb43adb467eac424253a13'
    ],
    [
      'e',
      'bbe609b05f19c1a030b414a34969a4207aee95b1fa3925e0a576f12724075b6f'
    ],
    [
      'e',
      'f8ac0ca0c9162f8c85e1ff21a590fc2e88b4a9184c90e26575473506ddc5086b'
    ],
    [
      'e',
      '260fe58bad3450aa6ee0369058a18efe9e8eb5fadcea413f79626a61a11e123a'
    ],
    [
      'e',
      '68cd454a730792a2e4af23a3cac07e340ed700211871313a3a132ecfb91119bf'
    ],
    [
      'e',
      '1d8bb1e63d38d3828c36b8695d8f72acf0fdd5698aecff32da5591f154ff606e'
    ],
    [
      'e',
      '7b9caafe3b83cf50a7c868a2b9d025a53ab515b1e3eb568ee2575018dee24e3b'
    ],
    [
      'e',
      'de1cb15d1fe2e87e82226b3b1425a3eed1e3e27e1656ab9239ce6d38102bf016'
    ],
    [
      'e',
      '0f0905794467660d20bab5f1a6b09447e203415d786a6437327faf97684c0b2d'
    ]
  ],
  pubkey: 'b3b0d247f66bf40c4c9f4ce721abfe1fd3b7529fbc1ea5e64d5f0f8df3a4b6e6',
  id: 'b60b741dc8d4aa249b20e78a524077571dc33af90f6f532c0249e257c58eeb96',
  sig: 'e25b2a8e52ab9008066d7df308e3c2428e73a652b73ba2112af74b25474e7d196b40e98fdcedbbcb4531d87bd89fbac672c6157cde566b904f324890e1f17dad'
}
```

**Comment by scsibug** [comment]
Keys in JSON need to be quoted (with double quotes).

Here is what it looks like corrected:

```
{
  "content": "updating relays",
  "kind": 5,
  "created_at": 1671853519,
  "tags": [
    [
      "e",
      "b7584184b0d47adb7452ac18ccc4071635757ce3c4f530205b8be42d7a6b4ffd"
    ],
    [
      "e",
      "f0c8d9e4058d924b0b0bc98e7f83e2037afc74177cdb43adb467eac424253a13"
    ],
    [
      "e",
      "bbe609b05f19c1a030b414a34969a4207aee95b1fa3925e0a576f12724075b6f"
    ],
    [
      "e",
      "f8ac0ca0c9162f8c85e1ff21a590fc2e88b4a9184c90e26575473506ddc5086b"
    ],
    [
      "e",
      "260fe58bad3450aa6ee0369058a18efe9e8eb5fadcea413f79626a61a11e123a"
    ],
    [
      "e",
      "68cd454a730792a2e4af23a3cac07e340ed700211871313a3a132ecfb91119bf"
    ],
    [
      "e",
      "1d8bb1e63d38d3828c36b8695d8f72acf0fdd5698aecff32da5591f154ff606e"
    ],
    [
      "e",
      "7b9caafe3b83cf50a7c868a2b9d025a53ab515b1e3eb568ee2575018dee24e3b"
    ],
    [
      "e",
      "de1cb15d1fe2e87e82226b3b1425a3eed1e3e27e1656ab9239ce6d38102bf016"
    ],
    [
      "e",
      "0f0905794467660d20bab5f1a6b09447e203415d786a6437327faf97684c0b2d"
    ]
  ],
  "pubkey": "b3b0d247f66bf40c4c9f4ce721abfe1fd3b7529fbc1ea5e64d5f0f8df3a4b6e6",
  "id": "b60b741dc8d4aa249b20e78a524077571dc33af90f6f532c0249e257c58eeb96",
  "sig": "e25b2a8e52ab9008066d7df308e3c2428e73a652b73ba2112af74b25474e7d196b40e98fdcedbbcb4531d87bd89fbac672c6157cde566b904f324890e1f17dad"
}
```

When that is put into the EVENT command format, you get:

```
["EVENT",{"content":"updating relays","kind":5,"created_at":1671853519,"tags":[["e","b7584184b0d47adb7452ac18ccc4071635757ce3c4f530205b8be42d7a6b4ffd"],["e","f0c8d9e4058d924b0b0bc98e7f83e2037afc74177cdb43adb467eac424253a13"],["e","bbe609b05f19c1a030b414a34969a4207aee95b1fa3925e0a576f12724075b6f"],["e","f8ac0ca0c9162f8c85e1ff21a590fc2e88b4a9184c90e26575473506ddc5086b"],["e","260fe58bad3450aa6ee0369058a18efe9e8eb5fadcea413f79626a61a11e123a"],["e","68cd454a730792a2e4af23a3cac07e340ed700211871313a3a132ecfb91119bf"],["e","1d8bb1e63d38d3828c36b8695d8f72acf0fdd5698aecff32da5591f154ff606e"],["e","7b9caafe3b83cf50a7c868a2b9d025a53ab515b1e3eb568ee2575018dee24e3b"],["e","de1cb15d1fe2e87e82226b3b1425a3eed1e3e27e1656ab9239ce6d38102bf016"],["e","0f0905794467660d20bab5f1a6b09447e203415d786a6437327faf97684c0b2d"]],"pubkey":"b3b0d247f66bf40c4c9f4ce721abfe1fd3b7529fbc1ea5e64d5f0f8df3a4b6e6","id":"b60b741dc8d4aa249b20e78a524077571dc33af90f6f532c0249e257c58eeb96","sig":"e25b2a8e52ab9008066d7df308e3c2428e73a652b73ba2112af74b25474e7d196b40e98fdcedbbcb4531d87bd89fbac672c6157cde566b904f324890e1f17dad"}]
```

That will parse, but it will fail on `nostr-rs-relay` because it is future-dated, and this relay tries to avoid storing events that claim to be made in the future.  Later today, this event will start working though.

**Comment by dskvr** [comment]
Thanks for your quick response! To clarify, I slipped up and sent your a debugged js object, not the JSON. The relay would recieve the JSON which would have double-quote encapsulated keys, my mistake! 

I'm not sure how my timestamps were post-dated, but that's almost certainly the cause. Sorry for consuming your time, but thank you so much for your response.

**Comment by dskvr** [comment]
Ok, so I found the post-date, I had accidentally added millis where I meant to add seconds, which put it very far into the future (good catch!). I completely removed post-dating, **however,** the event is still not being parsed.

I would like to clarify that I am publishing events using the same logic across my stack, this is the first event I've had issues with. When it comes to debugging `nostr-rs-relay` do you have any tips? Would love to dive into it and solve myself, and if I find something provide you with actionable steps.

**Comment by scsibug** [comment]
set the environment variable "RUST_LOG=info,nostr_rs_relay=trace" to get the most detailed info out of the code, without getting all the networking/tokio/hyper stuff.

Can you post the full EVENT command as the string you are sending over the websocket?

**Comment by dskvr** [comment]
It was an implementation error I somehow didn't notice, using `nostr-js` I had implemented `relay.send('EVENT', payload`), not `relay.send([event.payload])`. My blunder. Thanks for the debugging data and the bandwidth!
