### ISSUE TITLE
Event Kind 70202 Persisted to DB

### ISSUE THREAD

**Issue by leesalminen** [scsibug/nostr-rs-relay#34]
All of my relays are currently getting spammed with event kind=70202 to the order of multiple per second consistently for days.

IIUC, 70202 is an unclassified event kind per the NIPs.

Would it make sense to not persist (or even relay?) unclassified event kinds in the DB?

Or perhaps add an `event_kind_blacklist` to config.toml?

I'm open to submitting a PR for this, just looking for guidance on what's the preferred thing here.

**Comment by 0xtrr** [comment]
Yeah I want this too. Event kind 70202 is a good example of why it would be nice to be able to whitelist/blacklist certain kinds/kind ranges. I don't think we should block anything that isn't in the protocol yet but it would certainly help to be able to specify certain kinds or even ranges of kinds that are either whitelisted or blacklisted. The relay should probably also send a notice if the event isn't persisted.

I think this also makes sense besides fighting spam, for example for relays that only want to store NIP-28 related events for their chat app. Or Twitter-like clients that doesn't want to store event kinds that doesn't have any use in their client.

**Comment by leesalminen** [comment]
Confirmed the newly merged PR is working as intended for me and am successfully filtering out event kinds on my blacklist.
