### ISSUE TITLE
Any plans for expensive relay ?

### ISSUE THREAD

**Issue by ilazaridis** [scsibug/nostr-rs-relay#39]
Are there any plans for this ?

**Comment by FliKites** [comment]
Just curious, is that the type of relay that would post into the "global" channels of most clients?

I cant seem to get this relay to publicly relay. 

Is their something that needs to be set in the config?

**Comment by scsibug** [comment]
I have no plans.  AUTH and other protocol features probably need to shake out first.

**Comment by scsibug** [comment]
> Just curious, is that the type of relay that would post into the "global" channels of most clients?
> 
> I cant seem to get this relay to publicly relay.
> 
> Is their something that needs to be set in the config?

Maybe you should open a separate issue if you have a problem using the relay, with details of your setup.
