### ISSUE TITLE
POW limit support

### ISSUE THREAD

**Issue by 0xtrr** [scsibug/nostr-rs-relay#41]
It would be very helpful to be able to require a certain amount of zero bits, i.e. POW on note IDs, for events getting published to our relays. Will make spamming slower at the very least. Do you have any plans on supporting this?

**Comment by 0xtrr** [comment]
I mentioned this on the nostr Telegram group and there are some issues with this. Noting them down here to get a discussion going on this topic.

1. I'm not sure how we would communicate the POW difficulty to clients. There is nothing in [NIP-13](https://github.com/nostr-protocol/nips/blob/master/13.md) that says how relays should communicate this information.

2. How would clients handle it if different relays imposes different difficulties for the event? 
I guess this could be solved by mining the most difficult ID? Relays could effectively DOS the user by imposing an impossible difficulty but the user could just remove that relay then.

3. Some clients does not support NIP-13 yet, would render them unusable. I at least don't want to impose this restriction on my own relay yet until there is good support for it in clients.

4. Is it possible to dynamically set the difficulty per pubkey or IP based on e.g. events/sec or events/min? That would make it a lot harder to spam.

**Comment by scsibug** [comment]
I think in practice, clients will do the simple thing and just count leading zero bits as PoW.  NIP-13 is more sophisticated, great for clients producing PoW to implement, but consumers don't really need to care imo.

Sure - there are lots of ways to configure a relay to allow more events based on PoW; either on the pubkey or a note.  We have rate limiting in place for several areas, we could bypass or impose lower costs based on PoW.  The simplest thing would be to simply set a cutoff above which we bypass the rate limiter entirely (notes with >=32 bits are not rate limited).

I don't have short term plans to work on this, but would be open to patches.  I will probably implement it myself eventually, especially as PoW is more widely adopted in clients and actual notes on the network.

**Comment by scsibug** [comment]
This will be trivial to implement through an gRPC extension for admitting events, so that's probably the first place it will show up.  Track https://todo.sr.ht/~gheartsfield/nostr-rs-relay/46 for eventual completion of that.  It's recently become my primary focus as the spam problem has become...motivating.
