### ISSUE TITLE
auto vaccuum causing issue (last 2 commits)

### ISSUE THREAD

**Issue by mikedilger** [scsibug/nostr-rs-relay#45]
`ERROR r2d2: attempt to write a readonly database`

Apparently this can happen if several processes have the database open at the same time.

This commit works: cb283ac3161c64f0f11261b1a329a5158629a450
This commit doesnt: b7c87371667ff00379805f53350517d313650d55
I didn't check the commit in-between.

Cheers, and thanks for all the work you do.

**Comment by scsibug** [comment]
Should be fixed with 3dd0f2c.
