### ISSUE TITLE
tracing option prevents relay from running as a service

### ISSUE THREAD

**Issue by BlockChainCaffe** [scsibug/nostr-rs-relay#48]
Hi, I set up my relay and started is as a service in a EC2 on AWS. No docker etc
I tried to use the "tracing" option but then the serivce refuses to start due to some error

Jan 09 09:55:22 ip-172-31-4-37 systemd[1]: Started Nostr Relay.
Jan 09 09:55:22 ip-172-31-4-37 nostr-rs-relay[43073]: Jan 09 09:55:22.850  INFO nostr_rs_relay: Starting up from main
Jan 09 09:55:22 ip-172-31-4-37 nostr-rs-relay[43073]: thread 'main' panicked at 'failed to set global default subscriber: SetGlobalDefaultError("a global default trace dispatcher has already been set")', /root/.cargo/registry/src/github.>
Jan 09 09:55:22 ip-172-31-4-37 nostr-rs-relay[43073]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Jan 09 09:55:22 ip-172-31-4-37 systemd[1]: nostr-relay.service: Main process exited, code=exited, status=101/n/a
Jan 09 09:55:22 ip-172-31-4-37 systemd[1]: nostr-relay.service: Failed with result 'exit-code'.
Jan 09 09:55:23 ip-172-31-4-37 systemd[1]: nostr-relay.service: Scheduled restart job, restart counter is at 1.
Jan 09 09:55:23 ip-172-31-4-37 systemd[1]: Stopped Nostr Relay.

**Comment by scsibug** [comment]
Yep, the existing log/tracing setup is incompatible with simultaneously running tracing enabled.  I've added a check to ensure we don't try to run logging & tracing at the same time.

Thanks for reporting!
