### ISSUE TITLE
Message structure improvement proposal

### ISSUE THREAD

**Issue by rajarshimaitra** [scsibug/nostr-rs-relay#5]
Currently there is a custom serde deserializer for `Subscription` struct, while having a default serde serialization.

https://github.com/scsibug/nostr-rs-relay/blob/81e4e2b892c9c0aadbc113aa2ca53b9765be5f42/src/subscription.rs#L45

https://github.com/scsibug/nostr-rs-relay/blob/81e4e2b892c9c0aadbc113aa2ca53b9765be5f42/src/subscription.rs#L8-L12

This makes round trip serde serialization test fails. And also forces the code base to maintain localized custom deser.. logic.

I think this can be improved a bit.

 - Ideally We should have only one global `NostrMessage` which will know how to deserialize itself from a websocket message stream depending upon the `command`, `EVENT`, `REQ` or `CLOSE`. The ground work for it is already included in `protostream.rs`. Only this will include the custom serde_deser method.
 
  - The other message structs like `Event`, `Subscription`, and `Close` doesn't need to include the `cmd` String, and only the data it cares about. `cmd` strings are always static so we should not have to be storing them. Here we can use default serde stuffs and have compiler gurantee on deserialisation.
  
  - This should be done in a TDD mode with `NostrMessage` satisfying all the possible message boundaries. This will ensure the high level message parsing works as expected.

 - Testing would include all message types, which are only available for `Subscription` currently.

 - Testing should cover round-trips even though `serialization` may never be done. This ensures easy message format compatibility with protocol in future.   
 
 I am willing to work on these improvements. Opening this issue for further discussion.

**Comment by scsibug** [comment]
This all sounds worthwhile.  I would greatly like to see the proto stuff simplified.  Happy to accept PRs that make this all more idiomatic.  Much of this was a tokio/serde/websocket learning project, so I'm sure there is much to improve.

**Comment by rajarshimaitra** [comment]
Yup sounds good. I loved the way you started and kept it simple. It gives a good ground to build on. Will try to churn some love for protostream.

**Comment by scsibug** [comment]
I think Raja has moved on to a separate relay implementation, so closing this.

**Comment by scsibug** [comment]
I think Raja has moved on to a separate relay implementation, so closing this.
