### ISSUE TITLE
Set custom mysql database

### ISSUE THREAD

**Issue by FliKites** [scsibug/nostr-rs-relay#51]
Could this repo be easily configured with a standalone mysql database?

**Comment by scsibug** [comment]
Not yet.  Upcoming changes may replace rusqlite with sqlx, which should have a MySQL layer.

**Comment by FliKites** [comment]
Thanks for the quick reply. I'll look out for any updates. Take it easy.  ---- On Thu, 19 Jan 2023 17:13:38 -0500  ***@***.***  wrote ----
Not yet.  Upcoming changes may replace rusqlite with sqlx, which should have a MySQL layer.
