### ISSUE TITLE
Does this relayer supports ephemeral kinds?

### ISSUE THREAD

**Issue by tiero** [scsibug/nostr-rs-relay#54]
It seems to not relay correctly ephemeral message, from a quick lookup in the code I see this comment.
https://github.com/scsibug/nostr-rs-relay/blob/b094fbcabdc964cdcb31a133f89b7108d54435c8/src/bin/bulkloader.rs#L84

Can you confirm if this relayer enables querying ephemeral kinds?

**Comment by thesimplekid** [comment]
When it gets a ephemeral event it relays it to all currently subscribed, but does not save the event so it cant be queried later.

**Comment by scsibug** [comment]
Correct.  Sorry, I thought I commented on this already, bit it didn't take.

More work is needed to provide tighter bounds on the allowed timestamps for ephemeral events, and prevent infinite relay loops from developing, but this should be functional in recent releases.
