### ISSUE TITLE
Starting up stops at "listening on: 0.0.0.0:8080"

### ISSUE THREAD

**Issue by setavenger** [scsibug/nostr-rs-relay#57]
I'm following the instructions for the setup and it starts up fine but it just stops at `listening on: 0.0.0.0:8080`. The relay is not available probably because the other expected logs are not popping up and it's in fact not listening/ready yet.  There is nothing in the logs (posted them below). The same thing happens when I build from source and deploy without containers.
```
root@cluster:~/nostr-rs-relay# podman run -it --rm -p 7000:8080   --user=100:100   -v $(pwd)/data:/usr/src/app/db:Z   -v $(pwd)/config.toml:/usr/src/app/config.toml:ro,Z   --name nostr-relay nostr-rs-relay:latest
Jan 28 18:41:50.244  INFO nostr_rs_relay: Starting up from main
Jan 28 18:41:50.245  INFO nostr_rs_relay::server: listening on: 0.0.0.0:8080
```

**Comment by setavenger** [comment]
```
Jan 28 19:20:43.032  INFO nostr_rs_relay: Starting up from main
Jan 28 19:20:43.033  INFO nostr_rs_relay::server: listening on: 0.0.0.0:8080
Jan 28 19:20:43.036 DEBUG nostr_rs_relay::repo::sqlite: Database reader pool is waiting on the database to be created...
Jan 28 19:20:43.536 DEBUG nostr_rs_relay::repo::sqlite: Database reader pool is waiting on the database to be created...
Jan 28 19:20:44.036 DEBUG nostr_rs_relay::repo::sqlite: Database reader pool is waiting on the database to be created...
Jan 28 19:20:44.536 DEBUG nostr_rs_relay::repo::sqlite: Database reader pool is waiting on the database to be created...
```

That message comes over and over

**Comment by scsibug** [comment]
If the database exists but cannot be written, the relay will error out. If the database file is not present, and the writer fails to create it, you'll see this string of messages.

Looks like the root cause is the inability to create the database.  I'm going to work on a better error message when the database cannot be created.

What operating system / container runtime are you using?

**Comment by setavenger** [comment]
I've tried on linux and MacOS. Not sure what you mean with container runtime. I'm using podman as suggested.

**Comment by scsibug** [comment]
Just pushed commit bdd4e43, which changes the order of how database pools are created.  This should fix the problem you found.  Looks like it was introduced pretty recently with the reshuffling of database code.

Thanks for the report; let me know if the latest revision fixes this issue for you.

**Comment by setavenger** [comment]
Tried the new commit. Now I'm getting this error:

```
Jan 28 20:29:50.596  INFO nostr_rs_relay: Starting up from main
Jan 28 20:29:50.598  INFO nostr_rs_relay::server: listening on: 0.0.0.0:8080
Jan 28 20:29:50.602 ERROR r2d2: unable to open database file: /usr/src/app/db/nostr.db    
Jan 28 20:29:51.002 ERROR r2d2: unable to open database file: /usr/src/app/db/nostr.db    
Jan 28 20:29:51.802 ERROR r2d2: unable to open database file: /usr/src/app/db/nostr.db
```

**Comment by scsibug** [comment]
ok, I was just able to duplicate this problem while running as root.  Works as a normal user though (using unshare).

**Comment by setavenger** [comment]
Hmm ok. So I should try using a different user then. Doing that, I again run into this issue though `Error: please use unshare with rootless`

**Comment by scsibug** [comment]
I'd recommend running as a normal user, instead of root.  You can add the option "--user=0:0" to podman run, and then it should be able to write to the local directory root-owned directory you are mapping into the container.

Or, you can use some other user account (instead of UID zero).  Make a new user, ensure they own the data directory and config.toml, and then pass that account's UID/GID (--user=U:G).

**Comment by scsibug** [comment]
You get the "user unshare with rootless" error when you are running as a non-root user?

**Comment by setavenger** [comment]
yup, I also can't start a container because podman thinks my user doesn't own the directory for some reason. Looks like i have some debugging to do. I will try to setup the vm from scratch again and see what happens. I think something with the user creation was not done properly on my side. 

I got it working as root now so I know the process now. Thanks very much for your help, much appreciated.

**Comment by scsibug** [comment]
Good to hear, thanks for opening the issue, that was a good bug to squash early.
