### ISSUE TITLE
Opening a dev discussion channel

### ISSUE THREAD

**Issue by rajarshimaitra** [scsibug/nostr-rs-relay#6]
I am interested in a robust and fast rust based nostr relay, and would love to contribute in the work.

I think this library already gives a very good start, Thanks @scsibug. And a lot can be improved here. I think there's enough people to build cool clients. But someone gotta make the relays sexy. 😄 

Maybe its time to start a dev channel for this project somewhere? Or if it already exists feel free to point me.

**Comment by scsibug** [comment]
I have the basics setup over on SourceHut (tickets/mailing list), but it's just been me on the codebase so far.

We could use the dev mailing list here for more in-depth discussion:  https://lists.sr.ht/~gheartsfield/nostr-rs-relay-devel

**Comment by rajarshimaitra** [comment]
Is there any specific reason for sourcehut? I am seeing it for the first time and have no clue how to interact with it.

My proposal is to keep it simple:
 - Github for code
 - Discord for chats

That's where I am seeing most activities these days.

**Comment by scsibug** [comment]
Maybe telegram for chat, since that is where all the nostr discussion is happening already?

I'm using sourcehut because I don't like to depend on Microsoft-owned properties any more than necessary.  But I keep commits mirrored between both so it's easy for anyone to use.

**Comment by rajarshimaitra** [comment]
New Discord dev server opened at https://discord.gg/AEG5Z8AP
