### ISSUE TITLE
 NIP-05 verification of users not work 

### ISSUE THREAD

**Issue by acupofespresso** [scsibug/nostr-rs-relay#61]
when I enable  nip-05 verifiy, but i not work

[verified_users]

mode = "enabled"
domain_whitelist = ["test.domain"]

**Comment by scsibug** [comment]
What behavior are you seeing?  Are domains not on the white list being permitted... are events on the white list not being permitted?

**Comment by acupofespresso** [comment]
events on the white list not being permitted

**Comment by scsibug** [comment]
I'm not able to duplicate this.  Have you tried pushing the user's profile to the relay *first*?  That will give it a chance to query the domain and validate the address, prior to pushing random kind=0 or other events?

If that doesn't work, can you paste the following here:
* your `config.toml`
* output of running `RUST_LOG=debug ./target/release/nostr-rs-relay` for the entirety of the test.
* the kind=0 event for the user with the domain you are trying to whitelist.
* the other event you are trying to publish that is being denied.

That should be enough to fully duplicate any issue.  Thanks!

**Comment by acupofespresso** [comment]
After  pushing the user's profile to the relay, it works  : )

Thanks a lot !

**Comment by scsibug** [comment]
Great to hear, thanks for the report and testing!
