### ISSUE TITLE
add port configuration option

### ISSUE THREAD

**Issue by newearthmartin** [scsibug/nostr-rs-relay#62]
I'm trying to run nostr-rs-relay but I'm already using port 8080 for another service, so I get this error:

```
thread '<unnamed>' panicked at 'error binding to 0.0.0.0:8080: error creating server listener: Address already in use (os error 98)', /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.24/src/server/server.rs:79:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', src/main.rs:48:19
```

Please add an option to configure this port. Or if there already is one, please add it in the `--help`. Thanks!

**Comment by thesimplekid** [comment]
It can be set in the config.toml

https://github.com/scsibug/nostr-rs-relay/blob/2e42b1b86e6323b87611d9d14224722a60c02282/config.toml#L56

**Comment by vimagick** [comment]
@thesimplekid

How to use another config files not in current directory?
Thanks!

**Comment by thesimplekid** [comment]
Cant without #63

**Comment by scsibug** [comment]
#63 merged, so you can now maintain your config file wherever you want!
