### ISSUE TITLE
Add Event Information Check Feature

### ISSUE THREAD

**Issue by nailuoGG** [scsibug/nostr-rs-relay#65]
As a developer, I would like to request the addition of a feature to check event information in order to address the problem of a large amount of spam events.

The filter function should be able to take in the following parameters:

- Source IP of the event
-  Entire content of the event
- User Agent
- A handler to determine whether the event should be saved or rejected

This feature would allow developers to write their own filters to handle the problem of spam events and make it easier to maintain the integrity of the data.

Thanks for considering this feature request.

**Comment by scsibug** [comment]
Agreed.  The way this is going to work is you'll be able to define an external gRPC endpoint.  That will be sent the information about incoming events, and it will be able to accept/reject.

In addition to what you've suggested, we'll also likely have NIP-05 validation status and the origin header.

I'm slowly working on this, you can track it over here: https://todo.sr.ht/~gheartsfield/nostr-rs-relay/46

This will let you integrate non-Rust languages.  Python in particular has a rich set of options for spam classifiers, so this should open up a whole new realm of development.
