### ISSUE TITLE
Dynamically update whitelisted users from config.toml

### ISSUE THREAD

**Issue by pluja** [scsibug/nostr-rs-relay#68]
I'm thinking about creating a monero-paid relay based on nostr-rs-relay, and I'm testing things out. When the relay is running, if I add a pubkey to the `pubkey_whitelist` variable, it doesn't seem to update dynamically.

Furthermore, the pubkey_whitelist variable doesn't seem to have any effect when I use it...

**Comment by pluja** [comment]
Is there any possible way to dynamically add users to the whitelist? As in, when a user pays the invoice, it gets added?

**Comment by pluja** [comment]
I see, these restrictions are currently not implemented. Sorry for bothering. Any idea if this will get implemented anytime soon?

**Comment by scsibug** [comment]
This works now using the gRPC extension.  You can write a gRPC server that will check each event, and if it does not satisfy a criteria such as the pubkey being in your dynamic list, you can reject it with a message.  There is a simple (rust) example in https://github.com/scsibug/nostr-rs-relay/blob/master/nauthz_server_example/src/main.rs but you can write this is any language that supports gRPC.
