### ISSUE TITLE
Unable to startup after moving data 

### ISSUE THREAD

**Issue by dskvr** [scsibug/nostr-rs-relay#70]
data filled up my volume and I had to mount a new volume. After copying the directory to the new volume, I double checked permissions, and all looked good. I then symlinked the directory from where the directory was before. Booted up `nostr-rs-relay` and checked the logs...

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Some("database is locked"))', src/db.rs:86:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-ws-1' panicked at 'called `Result::unwrap()` on an `Err` value: Error(None)', src/db.rs:86:10
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', src/main.rs:49:19
Feb 10 21:20:26.823  INFO nostr_rs_relay: Starting up from main
Feb 10 21:20:26.824  INFO nostr_rs_relay::server: listening on: 0.0.0.0:8080
Feb 10 21:20:26.827  INFO nostr_rs_relay::server: db writer created
Feb 10 21:20:31.843 ERROR r2d2: database is locked
Feb 10 21:20:37.252 ERROR r2d2: database is locked
Feb 10 21:20:43.060 ERROR r2d2: database is locked
```

My first guess is that the database got corrupted when it filled up that first volume. 

Before I do the standard `sqlite` repair, do you have any tips, utilities or anything I should be aware of before doing so?

**Comment by thesimplekid** [comment]
Might be of use: 

https://github.com/scsibug/nostr-rs-relay/issues/38#issuecomment-1365887228

https://github.com/scsibug/nostr-rs-relay/issues/38#issuecomment-1366337739

**Comment by 0xtrr** [comment]
Last time I experienced a locked DB, I dumped the db into a new file
`echo ".dump" | sqlite old.db | sqlite new.db`

If you have a "-wal" file, I believe you should run `PRAGMA wal_checkpoint(2)` in your sqlite file too to ensure that everything is written to the database

**Comment by scsibug** [comment]
I do not have much experience with sqlite DBs that get locked, but I'd assume this is best handled through stackoverflow/google searches for troubleshooting.  We are just using the stock SQLite library, so all the standard advice for that system applies.
