### ISSUE TITLE
Will it consider implement NIP23

### ISSUE THREAD

**Issue by VegeBun-csj** [scsibug/nostr-rs-relay#81]
I noticed that nostr-rs-relay does not support long text at present, but there have been long text proposals a few days ago, such as [NIP23](https://github.com/nostr-protocol/nips/blob/master/23.md). Will you consider implementing this NIP?

**Comment by scsibug** [comment]
Why do you think we do not support "long text"?  NIP-23 does not require anything special from relays, except for NIP-33, which we already support.

The default maximum length of events is 128KB; however this is fully configurable, and could be extended to much larger values if desired.

**Comment by VegeBun-csj** [comment]
> Why do you think we do not support "long text"? NIP-23 does not require anything special from relays, except for NIP-33, which we already support.
> 
> The default maximum length of events is 128KB; however this is fully configurable, and could be extended to much larger values if desired.

oh, thanks! Greate

**Comment by VegeBun-csj** [comment]
ok, thanks!
