### ISSUE TITLE
protoc unknown flag --experimental_allow_proto3_optional

### ISSUE THREAD

**Issue by mikedilger** [scsibug/nostr-rs-relay#83]
I see you've done several commits to try to get protoc to work on different machines.

I'm on Ubuntu 20.04.5 LTS (Focal Fossa, bullseye/sid) which supplies 3.6.1.3-2ubuntu5 of protobuf-compiler
which complains with

````
  Compiling nostr-rs-relay v0.8.6 (/data/nostr/nostr-rs-relay)
error: failed to run custom build command for `nostr-rs-relay v0.8.6 (/data/nostr/nostr-rs-relay)`

Caused by:
  process didn't exit successfully: `/data/nostr/nostr-rs-relay/target/release/build/nostr-rs-relay-f8880fbac01359b8/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=proto/nauthz.proto
  cargo:rerun-if-changed=proto

  --- stderr
  Error: Custom { kind: Other, error: "protoc failed: Unknown flag: --experimental_allow_proto3_optional\n" }
````

Maybe I need to upgrade the OS to 22.04.1 LTS (Jammy Jellyfish)?

**Comment by scsibug** [comment]
I bet 22 will be recent enough with commit 35a1973.  I guess 20 has a version of protobuf compiler too old to even accept the experimental flag :/

**Comment by mikedilger** [comment]
Ubuntu 22 fixed it.

I tried to upgrade the VPS and ruined it and spent half a day rebuilding/configuring a new server.  But it did fix this issue.
