### ISSUE TITLE
Open to adding a stable docker tag?

### ISSUE THREAD

**Issue by chmac** [scsibug/nostr-rs-relay#84]
Firstly, let me say that I'm delighted to find https://hub.docker.com/r/scsibug/nostr-rs-relay. Makes running nostr-rs-relay a breeze! Thanks a lot.

I (presume) I'd prefer to stay on the stable release (0.8.2). But I couldn't find a `stable` tag on docker, only `latest` which seems to point to the same image as the testing release (0.8.7). Would you be open to adding a `stable` tag on docker hub?

**Comment by scsibug** [comment]
That is a great idea, will definitely implement.
