### ISSUE TITLE
Stress testing

### ISSUE THREAD

**Issue by otherlayer** [scsibug/nostr-rs-relay#86]
I used a little modified `noscl` to stress test relay and wanted to test my implementations and got some broken pipes:
`WARN nostr_rs_relay::server: IO error (cid: 3b36d2de, ip: "127.0.0.1"): Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
`

Anyone got some stress testing working, some other tool I could use and check?

`noscl: publish.go` just do `PublishEvent` in loop.

Got `Maximum concurrent subscription count reached`, but changing `max_subs` limit didn't help.

0.8.2 version

**Comment by scsibug** [comment]
Stress testing relays is challenging.  I've used artillery, but what you'll most likely find is that you end up benchmarking the benchmark tool, not the relay.  You'll probably want to ensure you have significantly more computational power available to the client/load tester than the relay (especially if your load tester is written in javascript - not sure about noscl).

If you are hitting max concurrent subscriptions, i'm pretty sure you've got some client that is opening subs, but not closing them.  If you can duplicate this not working though, let me know.

Broken pipes are most likely coming from a client that exited without cleanly shutting down.  Again, hard to diagnose without an isolated test case that shows where this is coming from.

**Comment by otherlayer** [comment]
Thanks for quick reply, will check artillery then, want to check if performance stays the same when using authorization client and my implementation of external event processing with grpc.
