### ISSUE TITLE
Does it support NIP50 and NIP56?

### ISSUE THREAD

**Issue by VegeBun-csj** [scsibug/nostr-rs-relay#87]
Does nostr-rust support NIP50(searching information) and NIP56(user report some bad user)?

**Comment by VegeBun-csj** [comment]
Thank you for your reply!
NIP50: I have observed that the current trust-relay supports `NIP12 (generic Tag Queries)`. Does it mean that this kind of query based on tag can basically meet the demand under the current weak demand?

**Comment by scsibug** [comment]
Yes, that kind of search is quite efficient and well-defined, so we can serve a lot of traffic with tag queries.

**Comment by VegeBun-csj** [comment]
thanks!
