### ISSUE TITLE
How to test connection

### ISSUE THREAD

**Issue by pfergi42** [scsibug/nostr-rs-relay#92]
How can we test if it's working. Port 8080 is open, but still can't connect when adding the relay in Coracle.

**Comment by thesimplekid** [comment]
Can you get to it via web browser should get "Please use a Nostr client to connect."

Does coracle require wss? I know some clients do you may need a reverse proxy to handle tls.

**Comment by pfergi42** [comment]
Yes! When I put this in the browser:

http://nostr.azte.co:8080/

I get this message:

Please use a Nostr client to connect.

**Comment by thesimplekid** [comment]
Yeah bet coracle requires tls youll have to set up a reverse proxy. The relays is working
![image](https://user-images.githubusercontent.com/8606367/221298300-f6ac9108-53b2-4d39-b230-b26535ce4792.png)

**Comment by pfergi42** [comment]
Ok great thank you!

I also confirmed using the nostr-tool you suggested:

user@nostr-relay:~/nostr-tool# nostr-tool -r wss://nostr.azte.co text-note -c "Hello World"
No private key provided, creating new identity
Private key: nsec193ncase2pfcfxxujhwtk8tnll25q70fzhpla74uytnvrhcwz03uqzv9jlv
Public key: npub1wecsux8h0vk3ppfl3nt26kerkw7gch5x9ka428mx7sgry6pngawqzvzykc
Published text note with id: note163uk6fy80fguydkzm4q2g8t29gvutpc2qfm0lwtanxgnlal3qhfshum94y

**Comment by pfergi42** [comment]
> Yeah bet coracle requires tls youll have to set up a reverse proxy. The relays is working ![image](https://user-images.githubusercontent.com/8606367/221298300-f6ac9108-53b2-4d39-b230-b26535ce4792.png)

Done! It's all working now. Great work here thank you.
