### ISSUE TITLE
Preserve client IP address when using reverse proxy

### ISSUE THREAD

**Issue by donnyxray** [scsibug/nostr-rs-relay#93]
When using a reverse proxy all clients appear to come from 127.0.0.1. 

This could be remedied by adding support for the [proxy protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt). Haproxy, Nginx, Traefik and other reverse proxies support this protocol.

I have no experience with programming in Rust, but did find [this module](https://docs.rs/proxy-protocol/latest/proxy_protocol/) that may be of use.

**Comment by scsibug** [comment]
We have a config option, network.remote_ip_header, which can read an http header containing the true source IP address.  This will then show up in logs, and be used for gRPC event admission.

Supporting the PROXY protocol would be nice, so I would gladly accept a patch, but the header method seems to be working fine for every deployment I am aware of.

**Comment by donnyxray** [comment]
Not sure how I overlooked that. That will work just fine. Thanks!
