### ISSUE TITLE
Relay not using config

### ISSUE THREAD

**Issue by pfergi42** [scsibug/nostr-rs-relay#95]
Hello, I'm running the relay in a nonstandard directory.

I don't think the relay is reading my `config.toml` file.

Do we need to specify the config file somehow when we start the relay?

**Comment by thesimplekid** [comment]
can be configured with  --config 
`nostr-rs-relay --config /etc/nostr-rs-relay/config.toml`

https://github.com/scsibug/nostr-rs-relay/pull/63

**Comment by pfergi42** [comment]
Thank you for the obvious answer!

**Comment by thesimplekid** [comment]
> `ExecStart=/usr/local/bin/nostr-rs-relay --config /opt/nostr-rs-relay/config.toml`

think you need to quote since it has spaces

`ExecStart="/usr/local/bin/nostr-rs-relay --config /opt/nostr-rs-relay/config.toml"`

**Comment by thesimplekid** [comment]
Ah think its 
`ExecStart=/usr/local/bin/nostr-rs-relay -- --config /opt/nostr-rs-relay/config.toml`

I don't have the service env set up but running 
`RUST_LOG=warn,nostr_rs_relay=info /opt/nostr-rs-relay/target/release/nostr-rs-relay --config /opt/nostr-rs-relay/config.toml` 
does not respect the argument and 

`RUST_LOG=warn,nostr_rs_relay=info /opt/nostr-rs-relay/target/release/nostr-rs-relay -- --config /opt/nostr-rs-relay/config.toml`

**Comment by hundehausen** [comment]
I have the same problem with the docker container. I think it reads the config, but does not provide the NIP-11 data I specified.

**Comment by pfergi42** [comment]
Unfortunately adding the extra '--' doesn't help me and actually seems to be unsupported for me:

```
root@nostr-relay:~# RUST_LOG=warn,nostr_rs_relay=info /opt/nostr-rs-relay/target/release/nostr-rs-relay -- --config /opt/nostr-rs-relay/config.toml
error: unexpected argument '--config' found

Usage: nostr-rs-relay [OPTIONS]

For more information, try '--help'.
root@nostr-relay:~#
```

**Comment by pfergi42** [comment]
I can't run that command with the extra "--" but when I run without, we can see we're on 0.8.8

```
root@nostr-relay:~# RUST_LOG=warn,nostr_rs_relay=info /opt/nostr-rs-relay/target/release/nostr-rs-relay --version
nostr-rs-relay 0.8.8
```

**Comment by anchelnl** [comment]
Here same docker and non docker 0.8.8 version no config loaded both new installs .. tried 0.8.2 config

**Comment by pfergi42** [comment]
> I've set it up to run as a service using this guide: https://github.com/BlockChainCaffe/Nostr-Relay-Setup-Guide
> 
> I've added it to the service config like this:
> 
> `ExecStart=/usr/local/bin/nostr-rs-relay --config /opt/nostr-rs-relay/config.toml`
> 
> But it still does not seem to acknowledge the settings in the config. When I view the process in vtop I can see it was started with this flag:
> 
> ![nostr-config](https://user-images.githubusercontent.com/4021240/221702503-56ea8d29-29cd-4742-854e-dfb7499e3caa.png)

I confirmed this should not be required, as the conf file should only be requried to exist in the /opt/nostr-rs-relay/ directory, which it does:

https://github.com/BlockChainCaffe/Nostr-Relay-Setup-Guide/issues/10#issuecomment-1453069651

Based on the other users have similar issue, could be a bug?

**Comment by pfergi42** [comment]
> remote_ip_header

This was a good improvement! I was able to find the redundant "remote_ip_header" line (even though both were already commented out). I removed one of them and restarted, and now nostr.watch says it can get the NIP-11 info:

https://nostr.watch/relay/nostr.azte.co

![nip11](https://user-images.githubusercontent.com/4021240/223560206-fb535091-bc02-4829-a003-6cd3912f8e5d.png)

But also says pubkeyError "pubkey is not set"

my config file has this line in it
`pubkey = "e08b8d662bc4dbf60f257786cc49b3afaadfe340233235fe7f661829a4631e80"`

Damus app also can't read description or contact info.

Getting so close now...

**Comment by pfergi42** [comment]
Finally solved it. The problem was in the config file the whole time. The example config provided in the reverse proxy setup guide is not compatible with this relay implementation. Be sure to use the example config file provided here.

**Comment by hundehausen** [comment]
How did you fix it? I used the config from this repo, and it still doesn't work.

**Comment by pfergi42** [comment]
> How did you fix it? I used the config from this repo, and it still doesn't work.

Are you using the reverse proxy setup?

1. Make sure your config file is in the correct (working) directory
2. Or specify it when starting the relay
3. Also make sure you don't have a duplicate line with this string in it: "remote_ip_header"

Drop your relay URL here and/or config and perhaps we can get some clues.
